major changes

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -83,15 +83,17 @@ curl --silent -o ngrok.zip -L "https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable
 unzip ngrok.zip -d $BUILD_DIR/bin > /dev/null 2>&1
 echo "done"
 
-if [ ! "${CUSTOM_MINECRAFT_VERSION:-""}" ]; then
-  minecraft_version=${MINECRAFT_VERSION:-"1.12.2"}
-  minecraft_url="https://s3.amazonaws.com/Minecraft.Download/versions/${minecraft_version}/minecraft_server.${minecraft_version}.jar"
-
-  echo -n "-----> Installing Minecraft ${minecraft_version}... "
-  curl -o minecraft.jar -s -L $minecraft_url
-  mv minecraft.jar $BUILD_DIR/minecraft.jar
-  echo "done"
+minecraft_version=${MINECRAFT_VERSION:-"1.18.1"}
+minecraft_url="$(cat $ETC_DIR/files.json | python -c "import json,sys;obj=json.load(sys.stdin);print(obj[\"server\"][\"${minecraft_version}\"][\"url\"])")"
+if [ -z "$minecraft_url" ]; then
+  echo "Could not find URL for Minecraft version $minecraft_version. Please check files.json."
+  exit 1
 fi
+
+echo -n "-----> Installing Minecraft ${minecraft_version}... "
+curl -o minecraft.jar -s -L $minecraft_url
+mv minecraft.jar $BUILD_DIR/minecraft.jar
+echo "done"
 
 if [ -n "${MINECRAFT_EULA:-""}" ]; then
   echo -n "-----> Accepting Minecraft EULA... "
